In [13]:
import pandas as pd
import numpy as np

In [14]:
train_para_ = pd.read_csv('./raw_dataset/train_para.csv', header=None)
train_ques_ = pd.read_csv('./raw_dataset/train_ques.csv', header=None)
train_label_ = pd.read_csv('./raw_dataset/train_label.csv', header=None)

test_para_ = pd.read_csv('./test_para.csv', header=None)
test_ques_ = pd.read_csv('./test_ques.csv', header=None)

print(train_para_.head())
print(train_ques_.head())
print(train_label_.head())
print(test_para_.head())
print(test_ques_.head())

          0         1         2         3         4         5         6  \
0  3.340594  0.000434  2.720928  4.408517  3.432302  9.481677  3.577184   
1  2.770955  8.997431  7.173936  3.773383  7.378616  7.840147  8.979185   
2  8.275599  6.714597  9.624436  0.856578  8.311163  9.188796  8.189455   
3  0.723634  5.515918  9.401365  7.161248  1.250709  6.536091  1.035218   
4  2.175709  9.530665  4.752073  1.585491  6.157041  3.044071  9.628096   

          7         8         9  
0  2.018318  1.663517  4.958070  
1  6.380727  3.806432  7.261397  
2  5.611096  0.685115  7.930753  
3  1.579414  6.157523  3.458007  
4  1.711489  6.915509  5.802961  
          0         1         2
0  6.559813  4.229264  6.387243
1  8.800270  9.939308  7.340850
2  7.828804  4.644677  1.380569
3  9.852654  7.612537  1.701998
4  6.884327  3.334372  1.696238
     0
0  0.0
1  1.0
2  0.0
3  1.0
4  0.0
          0         1         2         3         4         5         6  \
0  7.849226  5.193785  5.040225  6.6

In [15]:
t_p, v_p = train_para_[:-3200,:], train_para[-3200:,:]

TypeError: unhashable type: 'slice'

In [16]:
v_p = train_para_.head(32000-3200)
print(len(v_p))
v_p.head()
#v_p.to_csv('train_para.csv',header=None, index=None)
#v_p = pd.read_csv('train_para.csv', header=None)
#v_p.head()

28800


0         1         2         3         4         5         6  \
0  3.340594  0.000434  2.720928  4.408517  3.432302  9.481677  3.577184   
1  2.770955  8.997431  7.173936  3.773383  7.378616  7.840147  8.979185   
2  8.275599  6.714597  9.624436  0.856578  8.311163  9.188796  8.189455   
3  0.723634  5.515918  9.401365  7.161248  1.250709  6.536091  1.035218   
4  2.175709  9.530665  4.752073  1.585491  6.157041  3.044071  9.628096   

          7         8         9  
0  2.018318  1.663517  4.958070  
1  6.380727  3.806432  7.261397  
2  5.611096  0.685115  7.930753  
3  1.579414  6.157523  3.458007  
4  1.711489  6.915509  5.802961

In [17]:
v_p = train_ques_.head(32000-3200)
print(len(v_p))
v_p.head()
# v_p.to_csv('train_ques.csv', header=None, index=None)
# v_p = pd.read_csv('train_ques.csv', header=None)
# v_p.head()

28800


0         1         2
0  6.559813  4.229264  6.387243
1  8.800270  9.939308  7.340850
2  7.828804  4.644677  1.380569
3  9.852654  7.612537  1.701998
4  6.884327  3.334372  1.696238

In [18]:
v_p = train_label_.head(32000-3200)
print(len(v_p))
v_p.head()
#...
#...
#...

28800


0
0  0.0
1  1.0
2  0.0
3  1.0
4  0.0

In [19]:
v_p = train_para_.tail(3200)
len(v_p)
v_p.head()
#...
#...
#...

0         1         2         3         4         5         6  \
28800  2.926270  6.917750  4.714107  1.433675  8.964988  0.648070  3.769303   
28801  4.651942  3.200172  5.421760  5.164606  3.705000  9.955713  7.182072   
28802  3.734706  7.847850  7.051035  1.849784  7.353614  2.237498  7.347745   
28803  2.762652  8.694539  4.459950  4.775556  9.209529  8.434784  7.814437   
28804  6.897748  0.479243  7.203528  7.103861  6.083043  0.896054  9.354666   

              7         8         9  
28800  4.256394  9.661645  2.547954  
28801  3.875201  8.857617  1.240602  
28802  2.971413  9.245838  5.838442  
28803  5.399543  8.081086  0.328737  
28804  6.769038  7.170491  1.709356

In [20]:
v_p = train_ques_.tail(3200)
len(v_p)
v_p.head()
#...
#...
#...

0         1         2
28800  2.253285  0.349205  9.695214
28801  3.109855  1.325272  9.121063
28802  6.300726  6.220712  9.315506
28803  2.881694  7.713610  1.792259
28804  1.347753  8.072038  7.972371

In [21]:
v_p = train_label_.tail(3200)
len(v_p)
v_p.head()
#...
#...
#...

0
28800  0.0
28801  0.0
28802  0.0
28803  0.0
28804  1.0

In [22]:
train_para = train_para_.values
train_para

array([[  3.34059416e+00,   4.34353086e-04,   2.72092850e+00, ...,
          2.01831788e+00,   1.66351666e+00,   4.95806983e+00],
       [  2.77095535e+00,   8.99743126e+00,   7.17393616e+00, ...,
          6.38072710e+00,   3.80643220e+00,   7.26139651e+00],
       [  8.27559933e+00,   6.71459698e+00,   9.62443554e+00, ...,
          5.61109604e+00,   6.85115107e-01,   7.93075298e+00],
       ..., 
       [  7.90588609e+00,   2.00123633e+00,   2.80412537e+00, ...,
          5.31059394e+00,   1.33666814e-01,   8.34414473e+00],
       [  5.59578488e+00,   5.23561951e+00,   2.83417687e+00, ...,
          3.60652166e+00,   6.22736285e+00,   1.82773807e+00],
       [  7.71166865e+00,   5.02963421e+00,   3.66627131e+00, ...,
          3.85540363e+00,   2.95236061e+00,   3.00873782e+00]])

In [24]:
train_ques = train_ques_.values
train_ques

array([[ 6.55981252,  4.22926377,  6.38724347],
       [ 8.80026968,  9.93930839,  7.34085024],
       [ 7.82880399,  4.64467727,  1.38056938],
       ..., 
       [ 4.44990197,  4.75346386,  5.27605263],
       [ 4.32370964,  2.80831172,  1.34810197],
       [ 8.0672774 ,  7.27933267,  4.90093871]])

In [25]:
train_label = train_label_.values
train_label

array([[ 0.],
       [ 1.],
       [ 0.],
       ..., 
       [ 0.],
       [ 0.],
       [ 0.]])

In [27]:
test_para = test_para_.values
test_para

array([[ 7.84922581,  5.19378499,  5.04022455, ...,  6.26597817,
         9.77785774,  9.12223533],
       [ 2.77212571,  9.29889303,  4.87604831, ...,  3.11435685,
         9.37084746,  0.57808354],
       [ 2.96045434,  8.81606422,  5.54868724, ...,  8.76385398,
         8.78484201,  3.45050231],
       ..., 
       [ 7.00457453,  8.55319134,  7.38849296, ...,  6.50133885,
         7.40469989,  9.809315  ],
       [ 6.70391412,  6.11142894,  9.89939431, ...,  3.16122062,
         9.27841241,  1.35694589],
       [ 9.99811809,  9.79471676,  0.87324075, ...,  9.45370523,
         5.46666133,  0.33160126]])

In [29]:
test_ques = test_ques_.values
test_ques

array([[  4.06830382,   3.58090738,   6.53765827],
       [  8.62094869,  10.19827793,   7.38119322],
       [  8.79241876,   9.12155586,   4.61863478],
       ..., 
       [  7.7701379 ,   2.97736233,   3.92438312],
       [  7.24587313,  10.62806032,   5.62625953],
       [  5.20812934,   4.41953515,   8.46668749]])

In [30]:
print(train_label.shape)

(32000, 1)


In [32]:
def isclose(a, b, rel_tol=1e-9, abs_tol=0.0):
    return abs(a-b) <= max(rel_tol*max(abs(a), abs(b)), abs_tol)

def IsEqual(a, b ,c):
    return isclose(a, b) and isclose(a, c)
IsEqual(1, 1, 1)

True

In [33]:
def IsAnswer(p, q):
    Flag = 0
    for i in range(8):
        if IsEqual(p[i]-q[0], p[i+1]-q[1], p[i+2]-q[2]):
            Flag = 1
            return 1.0
    if Flag is 0:
        return 0.0

In [34]:
pred_label = []
for i in range(train_para.shape[0]):
    para = train_para[i]
    ques = train_para[i]
    label = train_label[i]
    pred_label.append(IsAnswer(para, ques))

In [35]:
np.argwhere(np.array(pred_label) - train_label.reshape(-1))

array([[    0],
       [    2],
       [    4],
       ..., 
       [31997],
       [31998],
       [31999]])

In [36]:
pred_label = []
for i in range(test_para.shape[0]):
    para = test_para[i]
    ques = test_ques[i]
    pred_label.append(IsAnswer(para, ques))

In [37]:
df = pd.DataFrame({'pred': pred_label})
df.head()

pred
0   0.0
1   0.0
2   0.0
3   1.0
4   0.0

In [38]:
# df.to_csv('test_pred.csv', header=None, index=None)
# test_pred = pd.read_csv('test_pred.csv', header=None)
# test_pred.head()